import pandas as pd
import sys
import os

# Add the project root to the path
sys.path.append(os.path.join(os.path.dirname(__file__)))

# Load the dataset
df = pd.read_csv('data/dataset.csv', encoding='ISO-8859-1')

print("=== Severity Distribution (Raw) ===")
print(df['Severity'].value_counts())
print()

print("=== Severity Distribution (After Preprocessing) ===")
from src.data import preprocess, load_dataset
cleaned_df = preprocess(load_dataset('data/dataset.csv'))
print(cleaned_df['Severity'].value_counts())
print()

print("=== Sample Data (After Preprocessing) ===")
print(cleaned_df[['Age', 'Sleep_Hours', 'Work_Hours', 'Physical_Activity_Hours', 'Social_Media_Usage', 'Severity']].head(10))
print()

print("=== Factors that influence Severity ===")
# Show some examples of different severity levels
print("Low Severity Examples:")
low_severity = cleaned_df[cleaned_df['Severity'] == 'Low'][['Age', 'Sleep_Hours', 'Work_Hours', 'Physical_Activity_Hours', 'Social_Media_Usage']].head(3)
print(low_severity)
print()

print("Medium Severity Examples:")
medium_severity = cleaned_df[cleaned_df['Severity'] == 'Medium'][['Age', 'Sleep_Hours', 'Work_Hours', 'Physical_Activity_Hours', 'Social_Media_Usage']].head(3)
print(medium_severity)
print()

print("High Severity Examples:")
high_severity = cleaned_df[cleaned_df['Severity'] == 'High'][['Age', 'Sleep_Hours', 'Work_Hours', 'Physical_Activity_Hours', 'Social_Media_Usage']].head(3)
print(high_severity)
print()

print("=== Sample Inputs for Different Severity Levels ===")
print("1. For None Severity (Best Mental Health):")
print("   Age: 25")
print("   Sleep_Hours: 8")
print("   Work_Hours: 40")
print("   Physical_Activity_Hours: 7")
print("   Social_Media_Usage: 1")
print("   Gender: Female")
print("   Occupation: IT")
print("   Country: USA")
print("   Consultation_History: No")
print("   Diet_Quality: Healthy")
print("   Smoking_Habit: Non-Smoker")
print("   Alcohol_Consumption: Non-Drinker")
print("   Medication_Usage: No")
print()

print("2. For Low Severity:")
print("   Age: 30")
print("   Sleep_Hours: 7")
print("   Work_Hours: 45")
print("   Physical_Activity_Hours: 4")
print("   Social_Media_Usage: 2")
print("   Gender: Male")
print("   Occupation: IT")
print("   Country: Australia")
print("   Consultation_History: No")
print("   Diet_Quality: Healthy")
print("   Smoking_Habit: Non-Smoker")
print("   Alcohol_Consumption: Occasional Drinker")
print("   Medication_Usage: No")
print()

print("3. For Medium Severity:")
print("   Age: 40")
print("   Sleep_Hours: 6")
print("   Work_Hours: 55")
print("   Physical_Activity_Hours: 2")
print("   Social_Media_Usage: 4")
print("   Gender: Male")
print("   Occupation: Healthcare")
print("   Country: USA")
print("   Consultation_History: Yes")
print("   Diet_Quality: Average")
print("   Smoking_Habit: Occasional Smoker")
print("   Alcohol_Consumption: Regular Drinker")
print("   Medication_Usage: Yes")
print()

print("4. For High Severity:")
print("   Age: 50")
print("   Sleep_Hours: 5")
print("   Work_Hours: 65")
print("   Physical_Activity_Hours: 1")
print("   Social_Media_Usage: 7")
print("   Gender: Male")
print("   Occupation: Sales")
print("   Country: Other")
print("   Consultation_History: Yes")
print("   Diet_Quality: Unhealthy")
print("   Smoking_Habit: Regular Smoker")
print("   Alcohol_Consumption: Regular Drinker")
print("   Medication_Usage: Yes")